### ISSUE TITLE
dialer-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/dialer-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Making the calls (*sputter cough cough*)

**Comment by dark-eye** [comment]
Hey I only have the Miezu PRO 5 phone so i probably can do much of the issue triaging related to other phone but i see That this app was without a maintiain for some time .... so.. hmmm.... can i be one? :smile:

**Comment by Flohack74** [comment]
Yes you can! Go ahead! :)
