### ISSUE TITLE
gradient on end-call button not good for contrast

### ISSUE THREAD

**Issue by Danfro** [ubports/dialer-app#101]
E5, devel 2020-01-15

Start a call.
The red end-call button apears.
The phone icon starts turning.
After turning has finished, the full red button does get a gradient added, with a darker end at the bottom.

This is not good for contrast and nothing I have seen in other places (button with gradient). I can not see a use/positive effect. Therefore I would suggest to remove this gradient.

![screenshot20200115_201204410](https://user-images.githubusercontent.com/37637312/72463755-45b05580-37d4-11ea-9b8c-626367456914.png)

**Comment by Flohack74** [comment]
@cibersheep will agree that this is against the Suru style guide right ;)

**Comment by cibersheep** [comment]
Suru Police is really concerned. How this could be possible :)
A fix will arrive soon™
