### ISSUE TITLE
Dialer repeatedly dies when starting

### ISSUE THREAD

**Issue by gmn** [ubports/dialer-app#11]
Hi, the Dialer has been dying for me. (I have a OnePlus One). Sometimes the dialer works. I got it to work randomly once this morning. But mostly I cannot get it started. Rebooting the device doesn't fix it. Oddly, I can still receive calls.  Here is a snippet which is representative of the log error I am seeing when it fails:

QIODevice::read: Called with maxSize < 0
QIODevice::read: Called with maxSize < 0
QIODevice::read: Called with maxSize < 0
QIODevice::read: Called with maxSize < 0
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
QIODevice::read: Called with maxSize < 0
QIODevice::read: Called with maxSize < 0

My Qt skills are rudimentary. I am not sure how I can determine which QML file or Qt component is being fed bad data which inturn enrages QIODevice. It seems utterly ludicrous to me that maxSize is not an unsigned type to begin with. I'll post any progress I can turn up here.

**Comment by gmn** [comment]
The macros which generate this error are all over qiodevice.cpp. I guess the next step is to get a list of which QObjects call or extend QIODevice, and then compare this list to which includes are used in Dialer. Maybe the problem can be tracked down that way..

**Comment by cyberpunkedu** [comment]
This seems to happen for me when connected to bluetooth. But works all right when starting from the phone directly.

Device: Hammerhead
Channel: 16.04/devel
Build: 2018-09-24

**Comment by lduboeuf** [comment]
@gmn , @userj  still happening ?

**Comment by cyberpunkedu** [comment]
Not sure, as not using hammerhead now.

**Comment by lduboeuf** [comment]
So lets close it for now
