### ISSUE TITLE
Dialer App In-Call Audio not working

### ISSUE THREAD

**Issue by ant0nwax** [ubports/dialer-app#110]
Hi community

we are developiong a UB ports for Samsung Note 4 (Snapdragon and Exynos).
This is about a QUESTION concerning In-Call Audio, not a bug

Linphone works as it should

Dialler-App In Call Audio works like the following now:
1. Initiate a call from or to UB ports Samsung Note 4
2. Pick up call
3. Microphone from Note 4 is not transmitted 
4. Ear Speaker or Speakerphone both remain silent
5. Plug in a headset is strange:
6. you can listen on the earbuds what you talk to the headset microphone

Any ideas how to debug this? We spent so much time with this already.

**Comment by Flohack74** [comment]
@ant0nwax are you already in our porting channel https://t.me/ubports_porting on Telegram?There we can talk better about it. While Apps like Linphone generate and record the sounds in memory and can send them directly up to  the sound driver, the sound from a call  needs to come from the modem and also go there again. For that there are non-trivial parts in the Android container that need to be set up correctly. So its not a simple configuration but needs to be analyzed properly.

**Comment by UniversalSuperBox** [comment]
Hi @ant0nwax, thanks for your report.

I hope you were able to get help using the porting Telegram channel. I'll close this report since no further discussion has been generated here.
