### ISSUE TITLE
ContactList / Favorite Sections not responsive

### ISSUE THREAD

**Issue by cibersheep** [ubports/dialer-app#116]
- Tap on contacts from main view
- Tap back
- Tap on Favorites tab
- Tap on Contacts tab
- Tap on Favorites tab before contact list is completed

Current behaviour: Favorites tab loads half or less of the times (maybe contact list is long)

Expected: tab changes accordanly

**Comment by lduboeuf** [comment]
@cibersheep still an issue ? How many contacts do you have ?

**Comment by cibersheep** [comment]
Thanks for remind me.
Now the behaviour is different: if you tap on Favorites tab before contact list is completed, the Section active is «Favorites» but the view if from all contacts. It might be an issue with Section element though.

I have about 270 entries

**Comment by lduboeuf** [comment]
and how many favorites ?
Also do you have a big call history database ?
Hardwate limitation ?

**Comment by cibersheep** [comment]
- 2 favorites
- A couple of years call history
- Tested on Arale Dev channel and E5 RC channel

**Comment by lduboeuf** [comment]
The call history also is freezing a bit for me ( but > 1000 call items....). But ok with contacts  ( > 250 contacts )

N5

**Comment by lduboeuf** [comment]
I think the new backend have better performance. I don't have the issue anymore on devel. Someone can confirm ?

**Comment by cibersheep** [comment]
I just tested on Mi A2 (latest dev) and I got a pretty nice response, no weird issues :)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/116

Sorry for your inconvenience.
