### ISSUE TITLE
Incoming call controls

### ISSUE THREAD

**Issue by userj** [ubports/dialer-app#12]
Implement incoming call controls:
- Block all calls 
- Block unknown numbers
- Block calls from numbers not in contacts
- Block individual numbers
- Forward certain calls to certain numbers 

These should be done silently with no interruptions.

**Comment by ghost** [comment]
See also ubports/dialer-app#18 and ubports/address-book-app#7

**Comment by lduboeuf** [comment]
Moved in favor of #18
