### ISSUE TITLE
Dialer-App - untranslated - German

### ISSUE THREAD

**Issue by openlewa** [ubports/dialer-app#124]
Please Fix. Thank you in advance.
![20200617_193633](https://user-images.githubusercontent.com/54738746/85210746-e1755d00-b342-11ea-9851-6a9efbd22441.jpg)

Dialpad tones = Tastentöne
Add an online account = Online-Konto hinzufügen

**Comment by lduboeuf** [comment]
@Alex-Lewa-95-RPI-Noob is this issue still there ?

**Comment by lduboeuf** [comment]
@fixed by e7b803a51bd6be0fdbbc52bc461773a4c2f3645b
