### ISSUE TITLE
"Add an online account" option does nothing

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/dialer-app#125]
The "Add an online account" option in the dialer's settings is grayed out, and nothing makes use of it. It is presumably for some SIP integration that never materialized.

The option should be removed until it has a purpose again.

**Comment by lduboeuf** [comment]
@mardy do you have an idea what was the status of SIP in dialer-app when canonical drop support ?, saw some commits from you around Ubuntu.OnlineAccounts and such.
