### ISSUE TITLE
Dial pad and alphabet

### ISSUE THREAD

**Issue by Thieb67k** [ubports/dialer-app#135]
Dear all,
I feel since the last UT update, below the number "3" within the dial pad, instead of "DEF" there is "IRD".
Plus, do those letters do something? That could be used to find a contact but I cannot write anything but numbers.
Best,
Thiebault

**Comment by lduboeuf** [comment]
Yes, strange, i see in translation DEF has been translated "IRD"...., can you ckeck this in weblate ?
I don't know if the letters used to work

**Comment by lduboeuf** [comment]
@Flohack74 , seems something wrong with translations on weblate ( conflicts ) https://translate.ubports.com/projects/ubports/dialer-app/

@Thieb67k  i've update the "DEF" issue but weblate seems blocked

**Comment by Flohack74** [comment]
It conflicts so much I cannot keep up with cleaning. Neither approach works, now we try to rebase each time before commit but no. I will try to find time for it...

**Comment by lduboeuf** [comment]
thanks @Flohack74 the translation seems to be fixed.

 @Thieb67k good question, i was asking myself for the letters. It would allow to search a contact theoretically but never get implemented

**Comment by lduboeuf** [comment]
@follow up here: https://github.com/ubports/dialer-app/issues/98
