### ISSUE TITLE
Minimal characters needed to start a search is 3 or 4? -ish?

### ISSUE THREAD

**Issue by kwoot** [ubports/dialer-app#156]
When wanting to search for a contact the search only begins after 3, sometimes 4, characters have been entered.
Used as I am to Google Contacts on the web it starts the search for a substring after the first character. 
Is it possible to change this?

**Comment by lduboeuf** [comment]
humm it starts searching on the 2nd character for me. Is it because you have lots of contacts and search takes time ?
BTW, database can be slow to query sometimes, have you tested by slowly typing ?

**Comment by kwoot** [comment]
Will verify. 
I do have lots of contacts yes (approximately 1700). But why is it slow? What is the backend? sqlite? no indexes?

**Comment by lduboeuf** [comment]
It can come from that, yes don't know why also why it can be so slow sometimes. Btw there is a work in progress to change the contact backend, hopefully it will be more performant.
There is no direct access to contact database, so several layers are used to access it.

**Comment by lduboeuf** [comment]
@kwoot  your use case could be interesting for testing the contact search via dial pad, can you try that feature ?
see here: https://github.com/ubports/dialer-app/pull/153#issuecomment-804940056

**Comment by lduboeuf** [comment]
Confirmed for me , the search for contacts is not responsive when typing fast, need to remove last letter often to have something, no issues found when doing search in address-book-app whereas it relies on the same Component

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/156

Sorry for your inconvenience.
