### ISSUE TITLE
enhancement : prevent accidentally answering a call while holding the phone upside down

### ISSUE THREAD

**Issue by YougoCodes** [ubports/dialer-app#176]
Using the UT device in any desired orientation -now even with a rotating lock screen- is great, but in the end, making phone calls (without using peripherals) requires the phone to orientated with the speaker up towards the ear and the mic down towards the mouth.

As many modern devices are indistinct black rectangles, not many visual clues exist to quickly discern whether the device is held upright or upside down. 

It could help if Dialer-app could force an upright orientation on phones, with Lomiri in 'staged mode' at least ('Desktop mode' and/or tablets with varying locations for mic and speakers complicate things...) so the app would provide the visual cue to which way is up.

A way to test the desired behavior is to do the following:

1. add this line, `X-Ubuntu-Supported-Orientations=portrait` to `/usr/share/applications/dailer-app.desktop`
2. close the Dialer-app if running
3. rotate the device to any position other than portrait
4. (you may lock the phone or not, but the behavior should be the same either way)
5. make a call to the device

The incoming call notification should appear at the top right

1. declining the call should leave the device as it is
2. accepting the call should start the Dialer-app, which promptly rotates the UI to portrait
3. ending the call leaves the Dialer-app active. as soon as another app is focused, rotation is released.

Modifying the .desktop file will overrule all other use cases. perhaps a switch or drop-down list can be placed inside the Dialer-app's settings to allow the user to define behavior?

**Comment by cibersheep** [comment]
Even this is a valid point, I think is a very specific issue. That can be worked out locking UI orientation from its indicator rather that forcing the rest of the user to use the Dialler on a specific orientation.

**Comment by Flohack74** [comment]
See also https://github.com/ubports/ubuntu-touch/issues/275

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/174

Sorry for your inconvenience.
