### ISSUE TITLE
 Possibility to add phone numbers to blacklist to block calls

### ISSUE THREAD

**Issue by trickyut** [ubports/dialer-app#18]
Hi,
I would like to ask to add possibility to add unwanted phone numbers to the blacklist to block incoming calls from certain phone numbers. It's quite hard to use phone on daily basis without this functionality.
Thanks!

**Comment by Stefano0101** [comment]
this feature would be highly appreciated!!!

**Comment by TomRausner** [comment]
It would also be nice if the phone could auto-play a prerecorded message, possibly one recorded to exactly that number...

**Comment by bwroga** [comment]
I would like to be able to have the phone ring for contacts and send all others to voicemail.

**Comment by Anne017** [comment]
I confirm that feature would be very useful.

**Comment by trickyut** [comment]
Is there any chance to add this feature request to 16.04 OTA-4 or 16.04 OTA-5?

**Comment by ghost** [comment]
Mock-up proposal here:
https://github.com/ubports/dialer-app/issues/31

**Comment by chdslv** [comment]
This is a very important request!

**Comment by TomRausner** [comment]
If the software is a problem... change the software NOW. This is a major problem to a lot of people !

**Comment by TartanSpartan** [comment]
I have the strongest of desires to see this implemented in time for OTA-8. Nuisance calls are now an hourly occurence for me and neither my phone nor my network provider can block them. I want to see Ubports catch up to Android and iPhone for this absolutely necessary feature.

**Comment by libermax** [comment]
Until this is implemented in dialer, a (non free) app exists named F-Call PRO that works for blocking calls (not for sms): https://forums.ubports.com/topic/1922/is-there-a-sms-phone-blacklist-app

**Comment by blueray453** [comment]
Is there any progress?

**Comment by vukitoso** [comment]
Hello. Call blocking already implemented?

**Comment by lduboeuf** [comment]
nothing new AFAIK. And even if some parts can be done on dialer, we need a system wide blocker accessible from address-book-app, dialer-app for calls, several services underneath and messaging-app for sms/mms
This is still a TODO, and i'm afraid if any volunteer don't take it, the core team is very busy moving system to 20.04, improve Lomiri and all stacks right now. But who know, that is something needed for lots of people, better ask on the forum and Q&A topic

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/18

Sorry for your inconvenience.
