### ISSUE TITLE
count of history entries to be deleted wrong

### ISSUE THREAD

**Issue by Danfro** [ubports/dialer-app#183]
Dialer app (on devel) provides an option to clear the call history. This counter seems to be wrong.

As you can see on the screenshots, selecting "one month" results in 13 entries. But when selecting "6 months" it comes up with zero. I would expect to show a minimum of 13 entries + any calls during the other five months. (it is my dev phone, so not many calls going on)

![grafik](https://user-images.githubusercontent.com/37637312/154000018-2d32cd71-17ba-4ca6-9a77-6b25cdda53a4.png)

![grafik](https://user-images.githubusercontent.com/37637312/154000027-eb8f7fd6-71fd-4531-9d9c-e948bb6aa2cb.png)

**Comment by Danfro** [comment]
I just found some more misbehaviours here.

Hopefully it can be seen on the screenshots, that there is one call entry in the call history. When selecting "1 month" the counter says "zero". When selecting "delete all" it shows 1. Both should show 1.

![grafik](https://user-images.githubusercontent.com/37637312/154001209-ca37b1b6-5073-45ed-9d52-8fe3a660c844.png)

![grafik](https://user-images.githubusercontent.com/37637312/154001228-b338fc10-9b7b-40bf-a70e-3872c292789d.png)

**Comment by lduboeuf** [comment]
humm, did you noticed that it count records older than the selected month ? 
e.g: selecting "6 month", will look at records before  6 month ago.

**Comment by Danfro** [comment]
Ahm. No. Feeling silly now. 

I obviously did not READ the text there. :innocent: Sorry about the noise. Does make even more sense to be able to select only old entries. 

Hmm. :thinking: If you press a button once, the label describing that "entries older than x" are going to be deleted is gone. Maybe for people like me, who press buttons before reading everything, it might be good to keep that label and add the counter label underneath? Or maybe add the counter label at the bottom above the two buttons?

But I close this anyway since it is no issue except me not reading. :smile:

**Comment by lduboeuf** [comment]
@Danfro yes could be something to do.  It can be confusing. At least we could disable "3 and 6 months" items if 1 month returns 0 and keep the initial label 
For the "hamburger" menu with only one item. I did that in case  we add one day another action.
