### ISSUE TITLE
UI: proposed changes to history clearing part

### ISSUE THREAD

**Issue by Danfro** [ubports/dialer-app#184]
From a UI point of view I would like to suggest some minor changes regarding call history.

1. The hamburger menu only holds one entry. This one icon should be shown directly. Even if a few more are added, they easily fit there. The menu should only be used when there are so many icons so they don't fit into the header.

![grafik](https://user-images.githubusercontent.com/37637312/154000546-7a763a34-ed8c-4ce2-8b9b-b84483e27437.png)

2. rename confirm button and change color

The button does not confirm a selection but actually triggers the deletion. I think it would be better to rename it to "delete" or "delete selected" and make it red colored.

![grafik](https://user-images.githubusercontent.com/37637312/154000325-258a9012-2534-49cb-8a74-5c814b4e9a3d.png)

**Comment by cibersheep** [comment]
@Danfro hi hi hi I just discovered the button text. Agreed:

Confirm -> Delete selected
- https://github.com/ubports/dialer-app/blob/xenial/src/qml/HistoryPage/HistoryCleaner.qml#L146

positiveText -> negative (the color property here is for the button, not for the text)
- https://github.com/ubports/dialer-app/blob/xenial/src/qml/HistoryPage/HistoryCleaner.qml#L147

**Comment by lduboeuf** [comment]
Sorry forgot to work on it :) .
If i don't forget, will have a look for next OTA cycle

**Comment by lduboeuf** [comment]
humm i did it but found the "delete selected" button text a bit weird. Never saw that before, why not just "delete" ?

**Comment by cibersheep** [comment]
:) Why weird?
«Delete» would work as well ^_^

**Comment by lduboeuf** [comment]
> :) Why weird? «Delete» would work as well ^_^

Just because i can't figure out how it can be translated in french ^ ^. I will replace with common "delete" then :)

**Comment by ivoxavier** [comment]
This feature, since it's inception, always worked well in all my devices. And still continues with this change. 
OnePlus 6T: ✅
Fairphone2: ✅

**Comment by Danfro** [comment]
Is it me, or is there no confirm dialog anymore? Xperia X, RC. But the hamburger menu is gone, just the bin icon, joined with the "tick all/untick all" icon.

**Comment by lduboeuf** [comment]
@Danfro were there a confirmation dialog before ? , i can't remember

**Comment by Danfro** [comment]
Sure, see the second screenshot in my first post when opening this issue.

**Comment by lduboeuf** [comment]
true this was requested but not existing. Will do it next
