### ISSUE TITLE
 Feature request- Display of the contact on call too small

### ISSUE THREAD

**Issue by xv1700** [ubports/dialer-app#197]
When I am called, the visibility of the phone number or contact name is too small and too weak. I can't see it without my glasses.
Is there a possibility to make this display larger when a call comes in?
The screen is big enough.
        Thank you!
![msg-1165295608-82641](https://user-images.githubusercontent.com/105711585/168776954-56e1ca98-168b-464c-9e01-1bec000f274e.jpg)

**Comment by lduboeuf** [comment]
Notifications style are set globally, so any modification on fontSize will apply on all notifications. Idk if it will play well for all, but i agree we could increase the size a bit.
@cibersheep  any advice ?

**Comment by lduboeuf** [comment]
here is an example, title is "x-large" instead of "medium" and subtext is "medium" instead of "small". A bit too big for simple text notifications. Maybe "large" would be enough

![notification](https://user-images.githubusercontent.com/11663835/168821859-22d2abd4-c223-4387-ad39-b45512eedcec.png)

**Comment by xv1700** [comment]
How to set this

**Comment by lduboeuf** [comment]
You can play with it here: /usr/share/unity8/Notifications/Notification.qml, just look at summaryLabel and bodyLabel fontSize

**Comment by xv1700** [comment]
with which programme can I do that?

**Comment by lduboeuf** [comment]
I guess if you are asking, you are maybe not familiar with the environment.
I think it is better not doing any hacking on the device directly if you don't know what you are doing ;-)

**Comment by lduboeuf** [comment]
Here it is by applying "large" fontsize on top label and "medium" on sub-text. 
This is the easiest solution for now. Bigger fonts  lead to proportional issues.
I can propose that


![notification2](https://user-images.githubusercontent.com/11663835/168864284-875ddb95-bc6e-4c79-9148-d65e44be38e6.png)


![screenshot20220517_183516721](https://user-images.githubusercontent.com/11663835/168868531-a7389f00-3c74-4cd3-8cf3-c502f94124f9.jpg)

**Comment by lduboeuf** [comment]
@xv1700 if you are on devel channel, it can be tested with `sudo ubports-qa install PR_unity8_438` ( and reboot )

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/177

Sorry for your inconvenience.
