### ISSUE TITLE
Add support for calling from 2 SIMs

### ISSUE THREAD

**Issue by ghost** [ubports/dialer-app#205]
You cannot call from 2 SIMs :- 'SIM 1' and ''SIM 2' in the app.

**Comment by Flohack74** [comment]
I am not sure I understand what you mean?

**Comment by ghost** [comment]
> I am not sure I understand what you mean?

When you dial a phone number which you want to call, after pressing the "call" button, you need to get two options :- "Call this number from SIM 1" and "Call this number from SIM 2". I discovered this feature in android's phone app in a few android devices. Not all devices running android have this feature but a few of them have this feature. But this feature can be added to UT as well.

**Comment by lduboeuf** [comment]
what about the section at the top where you can choose between the SIM cards ?:
see https://user-images.githubusercontent.com/37637312/46910068-478ac980-cf3e-11e8-82df-8a6ba5cdb9ef.png

**Comment by ghost** [comment]
> what about the section at the top where you can choose between the SIM cards ?: see https://user-images.githubusercontent.com/37637312/46910068-478ac980-cf3e-11e8-82df-8a6ba5cdb9ef.png

Instead of allowing them to exist as tabs, they need to appear only as popup options when the user presses the "Call"
 button.

**Comment by lduboeuf** [comment]
> Instead of allowing them to exist as tabs, they need to appear only as popup options when the user presses the "Call" button.

Well this is your opinion. Design is like that currently. IMO, it is better when we can avoid popups.

**Comment by lduboeuf** [comment]
> > what about the section at the top where you can choose between the SIM cards ?: see https://user-images.githubusercontent.com/37637312/46910068-478ac980-cf3e-11e8-82df-8a6ba5cdb9ef.png
> 
> Instead of allowing them to exist as tabs, they need to appear only as popup options when the user presses the "Call" button.

I think in system settings, when you choose "always ask" it popup something in dialer app when trying to call
