### ISSUE TITLE
When I dial a phone number, it should search for contacts that contains the numbers I dialled

### ISSUE THREAD

**Issue by mymike00** [ubports/dialer-app#3]
When I'm dialling a phone number, the app should search for contacts, or even recent calls etc..., that contains the numbers I've dialled.
It should be great if the app can search also for the corresponding letters (e.g. if I press '1' it searches also for contacts that contain/start with 'A', 'B' or 'C')!

**Comment by lduboeuf** [comment]
see https://github.com/ubports/dialer-app/issues/98 as a mockup

**Comment by mymike00** [comment]
cool, I missed it

**Comment by lduboeuf** [comment]
so i close it in favor of #98 and the pending PR #142
