### ISSUE TITLE
dialer-app: missed calls info is wrong Krillin vivid OTA:3

### ISSUE THREAD

**Issue by j2g2rp** [ubports/dialer-app#35]
Hi.
Yesterday i experienced a issue.

I had three missed calls. One of them is indexed as a missed call from a contact "A" but this number isn't from a contact at all. I still can reproduce it touching in the missed calls.
Additional info: In notification area the third missed call was shown from another contact "B" but the number wasn't also from that contact. I can't reproduce this since the notification is deleted. Maybe this isn't related to the other one.

There is any way to track it? If i can do something don't hesiate in ask for it.
Regards.

**Comment by lduboeuf** [comment]
@j2g2rp better late than never ;-).
Do you still reproduce the bug ?

**Comment by j2g2rp** [comment]
Nope, I had to reflash the phone since then and I didn't reproduced anymore.

Thanks @lduboeuf
