### ISSUE TITLE
[xenial] Call not displayed

### ISSUE THREAD

**Issue by GI9VANNI** [ubports/dialer-app#36]
Nexus 5 - 16.04 rc and 16.04 devel (2018-06-22)

I did a clean installation of Ubuntu Touch 16.04 rc on Nexus 5 and I'm finding a problem with the dialer.
Sometimes, especially the first time I use the dialer, when I start a call two problems can happen: either the dialer thinks the call has failed or the dialer remains impassive, as if I still had to type the numbers.
In any case, the call is regularly started, even if it is not displayed anywhere. The only way to end the call and make another call or turn off the device.

I've never had this problem with 15.04 OTA-3 on the same device.

**Comment by GI9VANNI** [comment]
I went from the clean installation of the 16.04 release candidate to the 16.04 devel and the issue remained.

[This video shows the problem better.](https://www.youtube.com/watch?v=7udH43DwUYg)

As you can hear the call continues even if the message _Chiamata non riuscita_ (_Call failed_ in English) appears.
I found the problem by calling 177 (my telephone operator's customer service).

**Comment by Flohack74** [comment]
I currently cannot reproduce this on hammerhead. I tried here a few calls, none of them were lost by the dialer.

**Comment by GI9VANNI** [comment]
You try to call short numbers, like 3 digits. They give me this problem.

**Comment by GI9VANNI** [comment]
After the dialer thinks the call has failed, even if the it is regularly started but is not displayed, I must do another call to stop the precedent call. [At the end of this last call, the dialer freezes.](https://github.com/ubports/ubuntu-touch/issues/739)

**Comment by cyberpunkedu** [comment]
This seems to happen for me when connected to bluetooth 
Device: Hammerhead
Channel: 16.04/devel
Build: 2018-09-24

**Comment by lduboeuf** [comment]
> You try to call short numbers, like 3 digits. They give me this problem.
Confirmed on N5
That low level issue is reported here: https://github.com/ubports/ofono/issues/14

**Comment by lduboeuf** [comment]
on N5, devel, there is not more the issue calling short number. There is still that weird "+3" appearing in the phone number field, but i can hang up without issue.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/36

Sorry for your inconvenience.
