### ISSUE TITLE
Cleanup of recent / missed calls necessary

### ISSUE THREAD

**Issue by Flohack74** [ubports/dialer-app#5]
I consider all aspects of not deleting data in a structured way as a bug in information systems.

That said, the dialer app does not clean up the list of recent or missed calls and neither has an option for the user to do it. This is really necessary, my list goes back 2 years now, and its getting slower and slower.

**Comment by ghost** [comment]
I agree. A good place for this option would be in the Settings of the app (with a link to the System Settings > Security & Privacy?).

**Comment by cibersheep** [comment]
On Dialer App:
- swipe up to show recent calls
- tap and hold on a recent call
- Tap on select all icon (top right)
- Tap on delete

But (always a but) if the list is reaaaaally long, app freezes and recent call list is not deleted

**Comment by lduboeuf** [comment]
So should we provide a bulk delete action button in the dialer-app ?
I don't like the idea of putting it in the settings except if we would like to define a max call history date or number , and as @cibersheep said, the long-press + select all + delete is a common feature on UT but only delete displayed call history.
So maybe an action button + confirmation dialog on top header in the call history screen ?

**Comment by Flohack74** [comment]
My list is now probably 5 years long lol.

**Comment by lduboeuf** [comment]
and doesn't it make the call history hardly scrollable ? So ideas welcome for Mockup or UX for a "clean all" action.

**Comment by ivoxavier** [comment]
Hi,

Tested on both FP2 and n5.

The records calculation for each filter worked correctly and deletetion worked as well.

Only missing the translations but that it a separate issue.

**Comment by dark-eye** [comment]
Tested on poco f1 seems to be working

**Comment by lsitongia** [comment]
Pixel 3a (GSMA).
I've been on the devel channel. I cleared all my recent calls. Then I switched to RC. Placed a call to my phone to get a recent call in the log. I CANNOT remove it now. The Confirm button will not become clickable. I placed another call to my phone and now I have two calls in the log, but the Call history window says 0. I've tried selecting all of the time period options.

**Comment by Flohack74** [comment]
@lduboeuf can you investigate?

**Comment by lduboeuf** [comment]
yes,  strange, i've just made a test but without switching to RC and no issue. 
@lsitongia do you see if the call record have a weird created date ?. Do you see anything in logs ?
and  what history-service package version do you have ?

**Comment by lduboeuf** [comment]
just tested the same use case. no isues for me, the "delete all" option find 1 record and i'm able to delete it

**Comment by lsitongia** [comment]
I just tried again and it worked correctly. There were no updates. I'm still running version 43, as I was before. I don't have a explanation. Even thought the button doesn't change the shade much, and looks greyed out, I'm sure I tapped on it multiple times.

-- 
Sent with Dekko - the convergent email app

**Comment by lsitongia** [comment]
Did another test: called my phone, answered and talked to myself for a bit. Hung up. Incoming call shows in Recent. Selected Clear History and tapped on Delete All. The count that is shown just below the title of "Call history" in that popup shows 0. I cannot clear the log.

I guess I'll wait until later today and tomorrow to see if there's some age threshold that must be crossed?

**Comment by Flohack74** [comment]
@lsitongia can you re-try? We want to release that in 2 days, so we kinda need a confirmation if and how it works :P

**Comment by lduboeuf** [comment]
> I guess I'll wait until later today and tomorrow to see if there's some age threshold that must be crossed?

If you select "Delete all" it should select all records that are older than "now". The only thing i'm thinking of is something with a Timezone/Date issue. Something interesting would be to see if you can delete them after some hours.

**Comment by lsitongia** [comment]
Yes, I think it is a matter of the time that has passed. I could not delete it an hour later, but I could two days later. I will do some experiments today to test this. Sorry I didn't try to delete after a few hours.

**Comment by lsitongia** [comment]
It's 9 hours later and I can clear the call I logged this morning. Maybe it is related to timezone? I'm GMT-7. I didn't check earlier. I could do this experiment again tomorrow and check before and after midnight GMT.

**Comment by lduboeuf** [comment]
@lsitongia 
> It's 9 hours later and I can clear the call I logged this morning. Maybe it is related to timezone?


Yes it is what i was thinking. Can you create an issue ?
 For now i have no idea where there can be an issue. I haven't touched anything related to call history storage.

**Comment by Flohack74** [comment]
Ok classified as non-release blocking, will analyze in next cycle.
