### ISSUE TITLE
Close dialer-app when finish a received call.

### ISSUE THREAD

**Issue by CesarHerreraG** [ubports/dialer-app#53]
This way you don't have to close it when you open the phone.

**Comment by Flohack74** [comment]
I dont think that suits all users, what if I want to make a second call immediately following?

**Comment by CesarHerreraG** [comment]
Optionally.

**Comment by CesarHerreraG** [comment]
Optional.

**Comment by cibersheep** [comment]
I do think this is a bad idea.
User must be always the one to close apps.

I would close this issue

**Comment by lduboeuf** [comment]
> I would close this issue
me too

**Comment by CesarHerreraG** [comment]
Close it then.
