### ISSUE TITLE
Dialer UP UI in landscape mode

### ISSUE THREAD

**Issue by Gabriele69** [ubports/dialer-app#6]
Hi, 
The keyboard interface rotated in landscape mode is incorrect. See attached photo

I use BQ Aquaris E4.5 Rc channel 6

**Comment by Gabriele69** [comment]
![screenshot20170925_164134951 1](https://user-images.githubusercontent.com/17642335/30814735-50cd4c94-a211-11e7-87d1-c000125fe56c.png)

**Comment by dobey** [comment]
How did you manage to get the dialer app to rotate? It has automaticOrientation set to false, and indeed does not rotate on my Nexus 5.

**Comment by dobey** [comment]
OK, I guess this only happens if you are already in landscape mode, and then start the app. You can work around this by editing `/usr/share/applications/dialer-app.desktop` and adding the line `X-Ubuntu-Supported-Orientations=portrait` to it.

**Comment by mateosalta** [comment]
This is also a usability issue for when using a Navigation app and accepting a call.

- In priority app for navigation, get call notification and accept call for 
- screen rotates while mounted landscape
- can not intuitively return to navigation

**Comment by Flohack74** [comment]
@dobey No it happens also when I start Dialer in portrait and then rotate. Just tried on the FP2 on 15.04 - apparently the code to prevent this is broken.

**Comment by lduboeuf** [comment]
should we then force dialer-app to be in portrait mode ?

**Comment by Flohack74** [comment]
For the time being its probably the best thing, otherwise you would have to redesign how the buttons etc are spread out.

**Comment by mateosalta** [comment]
![Screenshot_2020-10-27_21-08-36](https://user-images.githubusercontent.com/1965279/97383141-e4f19580-189a-11eb-8ff8-8a6de7304ba4.png)

old becomes new again? 
basic idea:
- dial pad on one side
- buttons and number field on the other
- please stop locking things down just for a bug on one phone

**Comment by lduboeuf** [comment]
so @Flohack74, do we revert it ?

**Comment by dobey** [comment]
> so @Flohack74, do we revert it ?

No. But if someone wants to make a PR to fix the landscape design of the app and make it more responsive, we can evaluate it for a future OTA for sure.

**Comment by mateosalta** [comment]
> so @Flohack74, do we revert it ?

fine for now, I just prefer letting more people getting eyes on it instead of papering over the cracks.

**Comment by lduboeuf** [comment]
@Flohack74 can we put this issue in the project board for OTA-15
