### ISSUE TITLE
Incoming call notification is intrusive

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/dialer-app#65]
Device: Hammerhead
Channel: devel
Build: 2019-03-28

The incoming call notification overrides all things  on the device.
You have to either answer or hangup, but you can't ignore it.
The rest of the screen is not functional while that is happening.

Even if you are calling someone else, and a call comes in, you can't hangup the current call or do anything other than address the incoming call. That is intrusive and takes the control away from the user.

**Comment by cyberpunkedu** [comment]
Also if you miss the swipe area to answer the call it sometimes swipes away the call completely.

**Comment by lduboeuf** [comment]
@userj  isn't it the expected behavior ? How behaves other platforms ?

**Comment by cyberpunkedu** [comment]
> @userj isn't it the expected behavior ? How behaves other platforms ?

I'm not sure about other platforms, but in any case I don't like the behaviour. May be just me.
The issue is either the first or the second thing mentioned.

If swiping away the call makes that notification stop and ignored, then it becomes an issue of easily swiping it away by accident when you are trying to answer it instead. Then that would be a different issue to note.

If swiping away doesn't cause the incoming call to stop and go away, then it's still an issue.

**Comment by cibersheep** [comment]
Agreed.
No notification bubble (or other element except PIN or Phrasecode) should block the UI

**Comment by lduboeuf** [comment]
So what is the expected behavior ?.
How should we ignore or go background the call notification from a UI/UX perspective ?

**Comment by cyberpunkedu** [comment]
I think swiping the call away to ignore/push to background is nice.
But, then to answer or reject a call, a completely different action is necessary. e.g. swiping up/down

**Comment by cibersheep** [comment]
> So what is the expected behavior ?.
> How should we ignore or go background the call notification from a UI/UX perspective ?

Like any other notification. User should be able to keep using the device even with incoming call notification on screen

**Comment by lduboeuf** [comment]
humm, need to see on other OSes how it is done

**Comment by cibersheep** [comment]
I think it would be better to focus on how UT should behave

**Comment by cibersheep** [comment]
I have checked the OS and the only two notification bubbles that block the UI are:
- incoming call
- Insert password in a new Wi-Fi connection
- headphone volume alert

I might missed any other.
The actual behavior is that you can swipe all of them to dismiss. Dismiss = cancel. In this case, it will reject the incoming call.

The only current difference is those three block the whole UI and they shouldn't. You should be able to keep typing, swiping, etc and then type the password, decide if it's ok to use high level of audio with headphones or accept/decline an income call.

Translate this to the desktop: You should be able to finish a text note while Wi-Fi bubble asks you for password.

**Comment by lduboeuf** [comment]
@cibersheep maybe need to be moved to general tracker i would say,

**Comment by cibersheep** [comment]
Agreed. Sorry.
I thought an issue was opened under the shell but I can't find it.

**Comment by nalysius** [comment]
I am in the same situation, the blocking notification prevents me from stopping the audio / video being played before answering, or just to continue using my phone while the notification is there. I have to either answer or decline.

To answer the question I saw in comments above, in Android, when receiving a call there is a notification quite similar to a "normal" OS notification, with just two buttons to answer or decline. The notification itself can be swiped and ignored, without declining the call. Also, the UI is not blocked so everything can still be used while the phone is ringing.

In UT we could imagine keeping the notification as it is, but changing a few things:
- make it not blocking. So any applications can still be used while the notification is there. We can finish to type a message or just pause a video before answering.
- add the possibility to swipe the whole notification (like a message notification) to ignore it. Note that _ignoring_ a call is different than _declining_ it.

**Comment by cibersheep** [comment]
>     * add the possibility to swipe the whole notification (like a message notification) to ignore it. Note that _ignoring_ a call is different than _declining_ it.

This is already implemented. But I should recheck if swiping the notification away hangs to the other party

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/65

Sorry for your inconvenience.
