### ISSUE TITLE
dialer app not accessible from other app during call

### ISSUE THREAD

**Issue by Danfro** [ubports/dialer-app#75]
E5 RC 2019-W27

When receiving an incoming call with another app open there is a green bar at the top saying something in the line of "tap here to return to the call/to open dialer app".

**Expected behaviour:**
- a tap onto that green bar opens dialer app

**Actual behaviour:**
- when tapping on that green bar nothing happens, dialer app is not accessible until the call has been finished

**Comment by tux4us** [comment]
OneplusOne dev 2019-07-01/2
Nexus5 rc 2019-W27

Same here

**Comment by Danfro** [comment]
Another user at the German group reports (E4.5), that this seems to occur on longer calls only. And when you tap the green bar several times you may eventually manage to open dialer app.

**Comment by cibersheep** [comment]
This happens on my E5 on the latests updates.
Dirty workaround: open dialer app from launcher

**Comment by Thieb67k** [comment]
Same issue on Nexus 4 (OTA-5-->10). But not frequent.

**Comment by lduboeuf** [comment]
someone still have that issue ?

**Comment by Thieb67k** [comment]
Danfro describes one green bar at the top when there is an incoming call. That green bar, in my case, appears when I want to hang up. In that case I do not see the keyboard with the red button (plus the screen is blinking). But it is not frequent.

**Comment by lduboeuf** [comment]
If you can test with that PR if it work ?: https://github.com/ubports/dialer-app/pull/134

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/75

Sorry for your inconvenience.
