### ISSUE TITLE
Screen remains blank during phonecall even when touchpad or power-button is pressed

### ISSUE THREAD

**Issue by Zatel** [ubports/dialer-app#8]
Device: Aquaris E4.5 Ubuntu Edition
OS: Ubuntu 15.04 (r2)

This bug began to appear with OTA 13, I think. When starting a phone call the screen immediately blanks, which is the correct behaviour. When I try to end the call I cannot access the screen to get to the red hang-up button. When I press the power-button the screen returns for half a second and then blanks again. So one has to wait until the other party hangs up - the screen reappears then after about 5 seconds. Of course, I also cannot reach the screen during the call for any extra functionality. The hardware is not at fault. To verify that I flashed the phone with Android which showcases the correct behaviour. I then reinstalled Ubports and the problem returned.

This bug is the only reason I cannot use the phone as my main device, so it would be great if this one could be solved.

**Comment by cibersheep** [comment]
Is this bug still happening on the latest OTA?

**Comment by Zorandon** [comment]
Yes, it is, the E4.5 is on OTA 9 and the behaviour is still exactly the same.

**Comment by lduboeuf** [comment]
@Zatel @Zorandon, still happening ?

**Comment by Zorandon** [comment]
Yes, on the BQ Aquaris E4.5 this always happens also on OTA-13.

  Fri, Oct 09, 2020 at 12:26:40AM -0700, Lionel Duboeuf wrote:

**Comment by lduboeuf** [comment]
I'm afraid it is not a dialer-app issue but it occurs at lower level. For the follow up : https://github.com/ubports/ubuntu-touch/issues/195

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/8

Sorry for your inconvenience.
