### ISSUE TITLE
Search a contact

### ISSUE THREAD

**Issue by dmaglio** [ubports/dialer-app#83]
With OTA-10 on OPO cannot search a contact from dialer.
In address-book work correctly (address-book-app closed issue [https://github.com/ubports/address-book-app/issues/56](url) )

**Comment by Flohack74** [comment]
Sorry, works for me. This must be a rare problem on your side ;)

**Comment by lduboeuf** [comment]
@dmaglio still the case ?

**Comment by lduboeuf** [comment]
@dmaglio I close that issue for now since no news, feel free to reopen or create a new one.
