### ISSUE TITLE
Dialler App on bluetooth

### ISSUE THREAD

**Issue by Julmuzy** [ubports/dialer-app#85]
OTA-9 on Aquarius e4.5
Dialler app switches to BT speakers and mic but no sound in either direction. Other apps connect and work correctly. BT system picks up incoming calls and acknowledges call cessation.  Switching to Ubuntu Phone option during call allows two way communication through the phone, but not BT, obviously.

**Comment by lduboeuf** [comment]
@Julmuzy, still hit this issue with OTA-13 ?

**Comment by Julmuzy** [comment]
Hello Lionel,

Yes, still the same. When I receive a call, the (car's) music player will stop but nothing comes from the car speakers, nor does the microphone work in the car kit. I have to manually select the speaker device to be Ubuntu phone (or loudspeaker) and then the call can proceed. Once the phone call stops, control is passed back to the car system and everything is ok. I can however use the car system through BT if I use the Music Player app or play something, (eg BBC radio 6) from the browser. Interestingly with these two apps, the default speaker is through BT and I do not need to select that option. This is why I believe the issue is with the dialer app and not with BT/ anything else.

**Comment by lduboeuf** [comment]
So we need to know if it is only a BQs issue or a more general issue

**Comment by phiibuntu** [comment]
Hi on ubports forum it seems to be on more general issue [https://forums.ubports.com/topic/7009/bluetooth-switches-off-during-telephone-calls/5?_=1641222662314](url) On my Xiaomi redmi note 9S on OTA-20 I have the same comportement. 
Phone call incoming in BT and then when I take the call it switch to phone speaker (BT icon stay, and switch manually to speaker and BT doens't change anything).

**Comment by lduboeuf** [comment]
So, better to create a global issue i would say in https://github.com/ubports/ubuntu-touch

**Comment by phiibuntu** [comment]
Ok thanks, I check it and there's many issue for the same bluetooth phone app problem, no need to create one more, I only comment one.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/85

Sorry for your inconvenience.
