### ISSUE TITLE
Is touch screen affected with dialer-App?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/dialer-app#87]
Dear all,
I experience some touch-screen's problems (loss of function) only with the dialer-app, like:
- not possible to pick up the incoming phone call.
- not possible to hang up (ubuntu-touch#195 by mgresko8; #456 by UKPhil).
- not possible to swipe the screen (only left-right swipe) (ubuntu-touch#991 by Thieb67k)
- full screen App disappear and not functionnal green notification bar appear (#75 by Danfro)

I wanted to gather in one post, issues described separately (because each of them happening with a different frequency), potentialy having a common point: the dialer-app.
I have nothing similar with other Apps and, as far as I know, no one has linked those issues previously. 

Did someone else have the same feeling?
Thanks

(Nexus 4, OTA-5-->10, stable channel)

**Comment by Flohack74** [comment]
Maybe its a faulty proximity sensor, does the screen stay on all the times? Did you try to cover/uncover proximity to see what happens?

**Comment by Thieb67k** [comment]
I cannot guarrantee that sensor works each time because I did not focus on that... (Is there any App for just basic users to test the sensor?)
But it often worked during phone call and recently worked whereas the green notification issue happened (#75 ). (I did not want to reduce the dialer App, it reduced by itself).
I will pay attention on that.

**Comment by Danfro** [comment]
I do experience that recently too (E5 devel channel), that I sometimes manage to activate flight mode with my ear when actually doing a call. Breaks the call though. :smile: 

The screen does sometimes flicker if I remove the phone from my ear, so the proximity sensor is not always working 100%. It does help to wipe the sensor! So I am not sure this is even created by sweat or the like covering the sensor and therefore creating this malfunction.
But I did have this issue more often recently and I think never the years before.

And I can not be sure, that after four years of age maybe my E5's proximity sensor might be faulty?

--------------------

Unable to hang up I can confirm too.

--------------------

Just for cross-referencing: [ubuntu-touch #195](https://github.com/ubports/ubuntu-touch/issues/195)  [ubuntu-touch #456](https://github.com/ubports/ubuntu-touch/issues/456)  [ubuntu-touch #991](https://github.com/ubports/ubuntu-touch/issues/991).

**Comment by lduboeuf** [comment]
anyone still experience that issue ?.

**Comment by Danfro** [comment]
I do not use my E5 for calling anymore, so I would not know. But I
suspected hardware issues where responsible.

**Comment by Thieb67k** [comment]
In my case, the third point (not possible to swipe the screen (only left-right swipe)) is still appearing in some cases.
Yet the touch screen feel something because:
- if a have the lock screen, I can swipe it.
- the dock can slightly appear (<10% of the full width) but hide again. I tried to take a picture but did not manage... Rebooting the phone "solve" that problem.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/87

Sorry for your inconvenience.
