### ISSUE TITLE
Can't compile Ubuntu 19.10

### ISSUE THREAD

**Issue by junocomp** [ubports/dialer-app#93]
I'm having a hard time compiling the app on Ubuntu 19.10. Is missing gcovr. Does anyone know if it is possible to run the app on x86 platform?

**Comment by junocomp** [comment]
I managed to compile and run the app but all it shows is a blank window.

**Comment by lduboeuf** [comment]
@giovannicaligaris, Still an issue ?

**Comment by lduboeuf** [comment]
there was some progress regarding building either with clickable or crossbuilder. Since no news from you, i close that issue for now, feel free to reopen if needed
