### ISSUE TITLE
Dial pad autocomplete (feature suggestion)

### ISSUE THREAD

**Issue by hscheewel** [ubports/dialer-app#98]
It would be nice to have this kind of optional functionality in the UT dialer app: When you want to call e.g. "Salvatore" type the numbers corresponding to the letters in his name in the right order (S → 7, A → 2, L → 5, ...). The app will then suggest at max 3 contacts (sorted alphabetically). Once the right contact appears you can select his/her name, the phone number will be passed to the keypad entry field and you are ready to call.

**A very simple dial pad autocomplete:**

->![Demo gif](https://raw.githubusercontent.com/hendrikscheewel/DialPadAutocompleteUT/master/demo.gif)<-

**Comment by lduboeuf** [comment]
so reverted previous PR because of wrong behavior, see #151

**Comment by lduboeuf** [comment]
@Flohack74 can you add this to the OTA-22 board ?

**Comment by lduboeuf** [comment]
For testers: 
The contact search is with firstname or lastname (starting with).  e.g, searching for "John" is by dialing 564
 If no contacts found with letters then there is a search by phone numbers. Favorites when fetched are shown first
This feature can be disabled/enabled in dialer app settings

**Comment by c4pp4** [comment]
RC OTA22: 2022-W04 (device: Mi A2)
Works (BTW great feature).

**Comment by c4pp4** [comment]
Just want to add one note. It can be disabled/enabled in settings from dialer app. The option is not available in system settings - phone.

**Comment by Flohack74** [comment]
@c4pp4 we could make this a feature request, yes

**Comment by gbdomubpkm** [comment]
When the phone is locked, which numbers can be accessed for emergency calls? Can all contact numbers be called or only certain predefined emergency contact numbers or certain official state numbers?
I say this because the autocomplete mechanism is active when you are on an emergency call, which suggests that anyone could guess, by dint of testing, the phone numbers of the contacts. Is this an intended mechanism?

**Comment by Flohack74** [comment]
You should only be able to call 112, 911 etc numbers

**Comment by lduboeuf** [comment]
humm ok, i suppose it search for contacts but we are not able to dial them. Better to disable that feature in case of emergency only. Will do, is it a blocker ?

**Comment by lduboeuf** [comment]
for the issue in emergency context https://github.com/ubports/dialer-app/issues/185

**Comment by Flohack74** [comment]
No its not a blocker.
