### ISSUE TITLE
in settings on dual sim devices only one phone number shown

### ISSUE THREAD

**Issue by Danfro** [ubports/dialer-app#99]
For the first sim card the IMEI number is displayed. For the second sim the phone number is displayed.

Likely related to [address-book-app #106](https://github.com/ubports/address-book-app/issues/106) and [system settings #197](https://github.com/ubports/system-settings/issues/197).

**Comment by lduboeuf** [comment]
As it is not related to dialer-app, i'm closing that issue now.
Some providers don't allow to store phone number(s) on SIM card
